# GAME CONSTANTS
MAX_THROWS = 9
MAX_DISTANCE = 9
BOARD_BOUNDARY = 4

# WEIGHTS FOR EVALUATION
BOARD_WEIGHT = 3
THROW_WEIGHT = 5
TOKEN_WEIGHT = 0.5
DISTANCE_WEIGHT = 0.2
INVINCIBLE_WEIGHT = 15

# DEPTH OF SEARCH
SIMULATE_DEPTH = 2

# LIMITS FOR CONSIDERING FUTURE
TOP_LEVEL_LIMIT = 25
RECURSIVE_LIMIT = 15
